[BTAT-9855] - Added penalties tile
hmrc/vat-agent-client-lookup-frontend pull request #241
Opened 2021-11-05 15:41 UTC by LewisMitchell

Raising as draft until #240 is merged.

See ticket to replicate.

https://user-images.githubusercontent.com/53828896/140537822-8194e2f1-adbd-4387-ae8b-6c88350772d8.mov

2021-11-05 15:47 UTC, LewisMitchell commented
App config base change: https://github.com/hmrc/app-config-base/pull/6379

2021-11-09 11:13 UTC, JoNB7777 requested changes

2021-11-09 11:46 UTC, JoNB7777 requested changes

2021-11-09 11:46 UTC, JoNB7777 commented on app/views/agent/partials/PenaltiesTilePartial.scala.html
> +        <p class="govuk-body">@messages("penaltiesTile.content")</p>
Can you please still add an ID for this line as well?

2021-11-09 11:46 UTC, JoNB7777 commented on test/views/agent/partials/PenaltiesTilePartialSpec.scala
> +  "PenaltiesTilePartial view" when {
Could you please select the elements by ID rather than by CSS selector in this file as it makes the tests more robust?

2021-11-09 11:46 UTC, JoNB7777 commented on test/controllers/agent/AgentHubControllerSpec.scala
> +      "the user has penalties" in {
Could you please also still add another test for when the user has no penalties?

2021-11-09 11:52 UTC, LewisMitchell commented
Need to also update the parser for 204 scenario

2021-11-10 09:16 UTC, LewisMitchell commented
App config staging change: https://github.com/hmrc/app-config-staging/pull/9428

2021-11-10 12:20 UTC, JoNB7777 approved these changes

2021-11-10 12:26 UTC, merged