BTAT-9987 update error message
hmrc/vat-agent-client-lookup-frontend pull request #248
Opened 2021-12-15 17:20 UTC by SheilaTran

2021-12-15 17:22 UTC, SheilaTran commented
**Please merge with: https://github.com/hmrc/change-vat-details-acceptance-tests/pull/191**

2021-12-16 09:51 UTC, lewishay requested changes

2021-12-16 09:51 UTC, lewishay commented on app/config/frontendAppConfig.scala
> +  override val agentClientServicesUrl: String = agentClientServicesHost + sc.getString(ConfigKeys.agentClientServicesUrl)
Can you remove lines 75 and 157 and simply update your URL value to be `sc.getString(host) + sc.getString(url)`? Looks unnecessary to me to make the host accessible like this when it's not being reused for any other purposes.

2021-12-16 09:51 UTC, lewishay commented on conf/application.conf
> +   host = "http://localhost:9448"
You will need to make an `app-config-base` PR to blank out this host in the environments

2021-12-16 11:20 UTC, SheilaTran commented
App-config-base PR: https://github.com/hmrc/app-config-base/pull/6528

2021-12-16 11:44 UTC, merged